"""M12 T2: TOPAS INP 文書ビルダ (純関数)。

`recipe`/`validity` と同じく **TOPAS 非依存の純関数**。tc.exe を起動せずテストできる。
出力はビット同一 (NFR-102)。

joint (複数ヒストグラム) の idiom は TOPAS 公式 Tutorial
``PDF Analysis/Joint Bragg-PDF Refinement/neutron_Si_corefinement.inp`` 準拠:
**構造パラメータはトップレベル ``prm`` に置き、各 ``xdd`` 内の ``str`` から ``=name;`` で参照する**
(TOPAS には GSAS の「1 相を複数ヒストグラムが共有する」ネイティブ機構が無いため)。
"""

from __future__ import annotations

import pytest

from tsumugin.topas.inp import (
    Param,
    PhaseHistogramTerms,
    TopasDocument,
    TopasHistogram,
    TopasPhase,
    TopasSite,
    render_param,
)

# ---------------- Param のレンダリング (TOPAS の @ / 名前 / ! の意味論) ----------------


def test_fixed_anonymous_param_is_a_bare_number():
    assert render_param(Param(9.18)) == "9.18"


def test_refined_anonymous_param_uses_at_sign():
    assert render_param(Param(9.18, refine=True)) == "@ 9.18"


def test_refined_named_param_is_name_then_value():
    """TOPAS では名前付きパラメータは既定で精密化対象 (`a lpa1 9.18`)。"""
    assert render_param(Param(9.18, refine=True, name="lpa1")) == "lpa1 9.18"


def test_fixed_named_param_is_prefixed_with_bang():
    """`!` 接頭辞が「名前は付けるが精密化しない」を表す (共有参照先の固定値に使う)。"""
    assert render_param(Param(9.18, name="lpa1")) == "!lpa1 9.18"


def test_bounds_are_appended_as_min_max():
    out = render_param(Param(9.18, refine=True, minimum=9.0, maximum=9.3))
    assert out == "@ 9.18 min 9.0 max 9.3"


def test_reference_renders_as_equation():
    """他パラメータの参照は `=name;` (joint の構造共有で使う中核)。"""
    assert render_param(Param.reference("lpa1")) == "=lpa1;"


def test_param_is_frozen():
    with pytest.raises(Exception):
        Param(1.0).value = 2.0  # type: ignore[misc]


# ---------------- 単一ヒストグラムの全体レンダリング ----------------


def _pbso4_phase(**kw) -> TopasPhase:
    return TopasPhase(
        phase_name="PbSO4",
        space_group="P_n_m_a",
        cell={"a": Param(8.482), "b": Param(5.397), "c": Param(6.959)},
        sites=(
            TopasSite("Pb", "Pb+2", Param(0.1879), Param(0.25), Param(0.1667), beq=Param(1.5)),
            TopasSite("S", "S", Param(0.4367), Param(0.75), Param(0.1842), beq=Param(0.7)),
        ),
        **kw,
    )


def _histogram(**kw) -> TopasHistogram:
    return TopasHistogram(
        data_path="pbso4.xye",
        preamble=("CuKa5(0.001)", "LP_Factor(26.37)"),
        background=Param(0.0, refine=True),
        background_coeffs=6,
        **kw,
    )


def test_single_histogram_document_is_a_stable_golden():
    doc = TopasDocument(
        histograms=(_histogram(),),
        phases=(_pbso4_phase(),),
        max_iterations=100,
    )
    assert doc.render() == (
        "' generated by tsumugin (do not edit by hand)\n"
        "r_p 0 r_wp 0 r_exp 0 gof 0\n"
        "r_wp_dash 0 r_exp_dash 0\n"
        "do_errors\n"
        "iters 100\n"
        "\n"
        "xdd \"pbso4.xye\"\n"
        "   CuKa5(0.001)\n"
        "   LP_Factor(26.37)\n"
        "   bkg @ 0.0 0.0 0.0 0.0 0.0 0.0\n"
        "\n"
        "   str\n"
        "      phase_name \"PbSO4\"\n"
        "      space_group P_n_m_a\n"
        "      a 8.482\n"
        "      b 5.397\n"
        "      c 6.959\n"
        "      site Pb x 0.1879 y 0.25 z 0.1667 occ Pb+2 1.0 beq 1.5\n"
        "      site S x 0.4367 y 0.75 z 0.1842 occ S 1.0 beq 0.7\n"
        "      scale 0.0001\n"
        "      MVW(0, 0, mvw_wt_PbSO4_h0 0)\n"
    )


def test_render_is_deterministic():
    """同じ入力からビット同一 (NFR-102)。"""
    a = TopasDocument(histograms=(_histogram(),), phases=(_pbso4_phase(),)).render()
    b = TopasDocument(histograms=(_histogram(),), phases=(_pbso4_phase(),)).render()
    assert a == b


def test_refined_cell_and_sites_carry_the_at_sign():
    phase = _pbso4_phase()
    phase = phase.with_updates(
        cell={k: Param(v.value, refine=True) for k, v in phase.cell.items()}
    )
    text = TopasDocument(histograms=(_histogram(),), phases=(phase,)).render()
    assert "      a @ 8.482\n" in text
    assert "      b @ 5.397\n" in text


def test_two_theta_limits_become_start_x_finish_x():
    hist = _histogram(two_theta_limits=(15.0, 120.0))
    text = TopasDocument(histograms=(hist,), phases=(_pbso4_phase(),)).render()
    assert "   start_X 15.0\n" in text
    assert "   finish_X 120.0\n" in text


def test_excluded_regions_become_exclude_blocks():
    hist = _histogram(excluded_regions=((37.5, 39.0), (44.0, 45.5)))
    text = TopasDocument(histograms=(hist,), phases=(_pbso4_phase(),)).render()
    assert "   exclude 37.5 39.0\n" in text
    assert "   exclude 44.0 45.5\n" in text


def test_neutron_histogram_declares_neutron_data():
    hist = _histogram(is_neutron=True)
    text = TopasDocument(histograms=(hist,), phases=(_pbso4_phase(),)).render()
    assert "   neutron_data\n" in text


def test_tof_histogram_uses_tof_block():
    hist = TopasHistogram(
        data_path="powgen.xye",
        is_neutron=True,
        is_tof=True,
        tof_calibration={"difc": 22580.0, "difa": -1.2, "zero": -4.5},
        background=Param(0.0, refine=True),
        background_coeffs=4,
    )
    text = TopasDocument(histograms=(hist,), phases=(_pbso4_phase(),)).render()
    assert "TOF_XYE(\"powgen.xye\", 0)" in text
    assert "TOF_x_axis_calibration(!difc_h0, 22580.0, !difa_h0, -1.2, !t0_h0, -4.5)" in text
    assert "   neutron_data\n" in text


def test_phase_histogram_terms_render_inside_the_str_block():
    """size/mustrain と scale は**ヒストグラムと相の組**に属する (GSAS の HAP と同じ概念)。"""
    hist = _histogram(
        phase_terms={"PbSO4": PhaseHistogramTerms(
            scale=Param(2e-4, refine=True),
            size_lorentzian=Param(200.0, refine=True),
            strain_lorentzian=Param(0.01, refine=True),
        )}
    )
    text = TopasDocument(histograms=(hist,), phases=(_pbso4_phase(),)).render()
    assert "      scale @ 0.0002\n" in text
    assert "      CS_L(@, 200.0)\n" in text
    assert "      Strain_L(@, 0.01)\n" in text


# ---------------- 結果出力ブロック (決定論的パース対象) ----------------


def test_result_output_block_emits_get_expressions():
    """T0 実測: `Out(Get(r_wp), ...)` が最も決定論的なパース対象。"""
    doc = TopasDocument(
        histograms=(_histogram(),), phases=(_pbso4_phase(),), results_path="results.txt"
    )
    text = doc.render()
    assert '   out "results.txt"\n' in text
    assert '   Out(Get(r_wp), "r_wp\\t%.8f\\n")\n' in text
    assert '   Out(Get(gof), "gof\\t%.8f\\n")\n' in text
    assert '   Out(Get(r_exp), "r_exp\\t%.8f\\n")\n' in text


def test_weight_fraction_is_emitted_per_phase():
    """相分率は MVW の weight を Out で吐く (wt% であって Scale ではない — KMnFe 教訓)。"""
    doc = TopasDocument(
        histograms=(_histogram(),), phases=(_pbso4_phase(),), results_path="results.txt"
    )
    text = doc.render()
    # 値側の書式に改行を入れない — 入れると esd が次行へ落ちる (実測)。1 レコード 1 行。
    assert '      Out(mvw_wt_PbSO4_h0, "wt_frac\\tPbSO4\\t%.8f", "\\t%.8f\\n")\n' in text


# ---------------- joint: 構造の共有 ----------------


def test_joint_hoists_structural_params_into_global_prm():
    """複数ヒストグラムでは構造を `prm` へ持ち上げ、各 xdd の str から `=name;` で参照する。"""
    xray = _histogram()
    neutron = TopasHistogram(
        data_path="pbso4.cwn.xye",
        is_neutron=True,
        preamble=("Lam_neutron(1.909)",),
        background=Param(0.0, refine=True),
        background_coeffs=4,
    )
    phase = _pbso4_phase()
    phase = phase.with_updates(cell={k: Param(v.value, refine=True) for k, v in phase.cell.items()})
    text = TopasDocument(histograms=(xray, neutron), phases=(phase,)).render()

    # グローバル prm に構造パラメータが一度だけ宣言される
    assert "prm PbSO4_a 8.482\n" in text
    assert text.count("prm PbSO4_a ") == 1
    # 各 xdd の str は参照式で書かれる (2 ヒストグラム = 2 回)
    assert text.count("      a =PbSO4_a;\n") == 2
    # 座標も共有される
    assert "prm !PbSO4_Pb_x 0.1879\n" in text  # 未解放は `!` 付き (joint でも段階解放が効く)
    assert text.count("site Pb x =PbSO4_Pb_x;") == 2


def test_joint_keeps_scale_and_background_per_histogram():
    """scale/背景/プロファイルは**共有しない** (ヒストグラム固有)。"""
    xray = _histogram(phase_terms={"PbSO4": PhaseHistogramTerms(scale=Param(1e-4, refine=True))})
    neutron = TopasHistogram(
        data_path="n.xye",
        is_neutron=True,
        background=Param(0.0, refine=True),
        background_coeffs=4,
        phase_terms={"PbSO4": PhaseHistogramTerms(scale=Param(5e-5, refine=True))},
    )
    text = TopasDocument(histograms=(xray, neutron), phases=(_pbso4_phase(),)).render()
    assert "      scale @ 0.0001\n" in text
    assert "      scale @ 5e-05\n" in text
    assert "prm PbSO4_scale" not in text  # scale は持ち上げない


def test_histogram_weight_becomes_weighting_directive():
    hist = _histogram(weight=2.5)
    text = TopasDocument(histograms=(hist,), phases=(_pbso4_phase(),)).render()
    assert "   weighting = 2.5;\n" in text


def test_unit_weight_omits_the_weighting_directive():
    text = TopasDocument(histograms=(_histogram(),), phases=(_pbso4_phase(),)).render()
    assert "weighting" not in text


# ---------------- 制約 (占有率和 = 1 / 等値) ----------------


def test_shared_occupancy_group_uses_one_prm_and_its_complement():
    """混合占有サイトは 1 変数 x と 1-x で表す (GSAS の add_EqnConstr 相当)。"""
    phase = TopasPhase(
        phase_name="garnet",
        space_group="I_a_-3_d",
        cell={"a": Param(12.19, refine=True)},
        sites=(
            TopasSite("Fe1", "Fe+3", Param(0.0), Param(0.0), Param(0.0),
                      occupancy=Param(0.5, refine=True), beq=Param(0.5)),
            TopasSite("Al1", "Al+3", Param(0.0), Param(0.0), Param(0.0),
                      occupancy=Param(0.5), beq=Param(0.5)),
        ),
        occupancy_sum_groups=(("Fe1", "Al1"),),
    )
    text = TopasDocument(histograms=(_histogram(),), phases=(phase,)).render()
    # 【`!` 付きで宣言】: TOPAS の名前付き prm は既定で精密化対象なので、解放前は固定する。
    # これが無いと段階解放を無視して最初の段から占有率が動き、occupancy 段が空振りする。
    assert "prm !garnet_occ_g0 0.5 min 0 max 1\n" in text
    assert "occ Fe+3 =garnet_occ_g0;" in text
    assert "occ Al+3 =1-garnet_occ_g0;" in text


def test_equivalent_beq_group_shares_one_prm():
    phase = TopasPhase(
        phase_name="garnet",
        space_group="I_a_-3_d",
        cell={"a": Param(12.19)},
        sites=(
            TopasSite("Fe1", "Fe+3", Param(0.0), Param(0.0), Param(0.0), beq=Param(0.5)),
            TopasSite("Al1", "Al+3", Param(0.0), Param(0.0), Param(0.0), beq=Param(0.5)),
        ),
        beq_equiv_groups=(("Fe1", "Al1"),),
    )
    text = TopasDocument(histograms=(_histogram(),), phases=(phase,)).render()
    assert "prm !garnet_beq_g0 0.5\n" in text  # 解放前は `!` 付き (段階解放を効かせる)
    assert text.count("beq =garnet_beq_g0;") == 2


# ---------------- 安全性 ----------------


def test_data_paths_with_backslashes_are_quoted():
    """Windows パスがそのまま埋まっても INP が壊れないこと。"""
    hist = _histogram()
    hist = hist.with_updates(data_path=r"C:\data\my run\pbso4.xye")
    text = TopasDocument(histograms=(hist,), phases=(_pbso4_phase(),)).render()
    assert 'xdd "C:\\data\\my run\\pbso4.xye"' in text


def test_phase_name_with_spaces_is_quoted():
    phase = _pbso4_phase().with_updates(phase_name="lead sulfate")
    text = TopasDocument(histograms=(_histogram(),), phases=(phase,)).render()
    assert '      phase_name "lead sulfate"\n' in text


def test_group_prms_are_released_only_when_asked():
    """共有 prm の `!` が段階解放そのもの。解放フラグを立てると `!` が外れる。"""
    phase = TopasPhase(
        phase_name="g", space_group="I_a_-3_d", cell={"a": Param(12.19)},
        sites=(
            TopasSite("Fe1", "Fe", Param(0.0), Param(0.0), Param(0.0),
                      occupancy=Param(0.5), beq=Param(0.5)),
            TopasSite("Al1", "Al", Param(0.0), Param(0.0), Param(0.0),
                      occupancy=Param(0.5), beq=Param(0.5)),
        ),
        occupancy_sum_groups=(("Fe1", "Al1"),),
        beq_equiv_groups=(("Fe1", "Al1"),),
        release_occupancy_groups=True,
        release_beq_groups=True,
    )
    text = TopasDocument(histograms=(_histogram(),), phases=(phase,)).render()
    assert "prm g_occ_g0 0.5 min 0 max 1\n" in text  # `!` が外れている
    assert "prm g_beq_g0 0.5\n" in text


def test_joint_scale_names_differ_per_histogram():
    """**scale は相とヒストグラムの組に属する** — joint で同名を宣言すると強制連結される。

    fix #5 で TCHZ の名前衝突を直しながら、fix #6 で scale に同じ罠を再導入していた
    (round 2 レビューで検出)。TOPAS のパラメータ名は大域であることを繰り返し忘れやすい。
    """
    xray = _histogram(phase_terms={"PbSO4": PhaseHistogramTerms(scale=Param(1e-4, refine=True))})
    neutron = TopasHistogram(
        data_path="n.xye", is_neutron=True,
        background=Param(0.0, refine=True), background_coeffs=4,
        phase_terms={"PbSO4": PhaseHistogramTerms(scale=Param(5e-5, refine=True))},
    )
    text = TopasDocument(
        histograms=(xray, neutron), phases=(_pbso4_phase(),), results_path="results.txt"
    ).render()
    names = [ln.split()[1] for ln in text.splitlines() if ln.strip().startswith("scale ")]
    assert len(names) == 2
    assert names[0] != names[1], f"joint で scale 名が衝突している: {names}"


def test_single_histogram_scale_name_is_still_stable():
    text = TopasDocument(
        histograms=(_histogram(),), phases=(_pbso4_phase(),), results_path="results.txt"
    ).render()
    assert "PbSO4_scale_h0" in text


def _collect_declared_names(text: str) -> "dict[str, int]":
    """INP 中で**宣言**されるパラメータ名を数える (参照 `=name;` は含めない)。"""
    import collections
    import re

    counts: collections.Counter[str] = collections.Counter()
    for raw in text.splitlines():
        line = raw.strip()
        if line.startswith("prm "):
            counts[line.split()[1].lstrip("!")] += 1
        for pattern in (
            r"occ \S+ !?([A-Za-z_]\w*) ",
            r"beq !?([A-Za-z_]\w*) ",
            r"MVW\(0, 0, (\w+) 0\)",
            r"^scale !?([A-Za-z_]\w*) ",
        ):
            match = re.search(pattern, line)
            if match:
                counts[match.group(1)] += 1
    return dict(counts)


def _joint_document() -> TopasDocument:
    phase = TopasPhase(
        phase_name="PbSO4", space_group="Pnma",
        cell={"a": Param(8.48, refine=True), "b": Param(5.40), "c": Param(6.96)},
        sites=(
            TopasSite("Pb", "Pb", Param(0.19, refine=True), Param(0.25), Param(0.17),
                      occupancy=Param(1.0, refine=True), beq=Param(1.5),
                      free_coord_axes=("x", "z")),
        ),
        free_cell_keys=("a", "b", "c"), free_occupancy_labels=("Pb",),
    )
    xray = TopasHistogram(
        data_path="x.xye", background=Param(0.0, refine=True),
        phase_terms={"PbSO4": PhaseHistogramTerms(scale=Param(1e-4, refine=True))},
    )
    neutron = TopasHistogram(
        data_path="n.xye", is_neutron=True, background=Param(0.0, refine=True),
        phase_terms={"PbSO4": PhaseHistogramTerms(scale=Param(5e-5, refine=True))},
    )
    return TopasDocument(histograms=(xray, neutron), phases=(phase,), results_path="r.txt")


def test_no_parameter_name_is_declared_twice_in_a_joint_document():
    """**TOPAS のパラメータ名は大域**。同名を 2 度宣言すると衝突するか強制連結される。

    この罠は 3 度別々の箇所で出た (TCHZ → scale → occ/beq/MVW)。個別に潰すのでなく
    「宣言名の重複が無い」を 1 本の不変条件として固定する。
    """
    duplicates = {k: v for k, v in _collect_declared_names(_joint_document().render()).items()
                  if v > 1}
    assert not duplicates, f"joint で名前が重複している: {duplicates}"


def test_structural_params_are_hoisted_and_shared_in_joint():
    """構造 (格子/座標/占有率/beq) はどの検出器で測っても同じなので共有する。"""
    text = _joint_document().render()
    for key in ("PbSO4_a", "PbSO4_Pb_x", "PbSO4_Pb_occ", "PbSO4_Pb_beq"):
        assert f"prm !{key} " in text or f"prm {key} " in text, f"{key} が持ち上げられていない"
        assert text.count(f"={key};") == 2, f"{key} が両方の xdd から参照されていない"


def test_hoisted_params_respect_staged_release():
    """joint でも `!` で段階解放が効くこと。

    持ち上げた prm を `!` 無しで宣言すると **最初の段から全構造が動く** (単一ヒストグラム
    経路では起きないので実データで気づきにくい)。
    """
    text = _joint_document().render()
    assert "prm PbSO4_a 8.48" in text  # 解放済み → ! 無し
    assert "prm !PbSO4_b 5.4" in text  # 未解放 → ! 付き
    assert "prm !PbSO4_Pb_beq 1.5" in text


def test_results_block_is_emitted_once_even_in_joint():
    """`out "file"` は append 無しだと**切り詰めて**開く。

    xdd ごとに出すと joint で 2 本目が 1 本目のレコードを消し、r_wp すら残らない。
    """
    text = _joint_document().render()
    assert text.count('out "r.txt"') == 1


def test_joint_still_emits_the_structural_publication_values():
    """**持ち上げたから skip** にすると joint でセルが 1 度も出力されず

    `refined_cells`/`cell_esd`/`atom_*` が静かに空になる。持ち上げ先の名前を指して出す。
    """
    text = _joint_document().render()
    # INP には**リテラルの** `\t` (バックスラッシュ + t) が入るので raw 文字列で書く。
    for record in (r"cell\tPbSO4\ta", r"coord\tPbSO4\tPb\tx", r"occ\tPbSO4\tPb"):
        assert text.count(record) == 1, f"{record} が 1 回出力されていない"


def test_structural_out_records_are_not_duplicated_per_histogram():
    """構造は全ヒストグラム共通の 1 つの量。xdd ごとに出すと同じレコードが重複する。"""
    import collections

    text = _joint_document().render()
    outs = [ln.strip() for ln in text.splitlines() if ln.strip().startswith("Out(")]
    dupes = [k for k, v in collections.Counter(outs).items() if v > 1]
    assert not dupes, f"Out が重複している: {dupes}"
