"""M12 T2: TOPAS INP 文書ビルダ (純関数)。

`recipe`/`validity` と同じく **TOPAS 非依存の純関数**。tc.exe を起動せずテストできる。
出力はビット同一 (NFR-102)。

joint (複数ヒストグラム) の idiom は TOPAS 公式 Tutorial
``PDF Analysis/Joint Bragg-PDF Refinement/neutron_Si_corefinement.inp`` 準拠:
**構造パラメータはトップレベル ``prm`` に置き、各 ``xdd`` 内の ``str`` から ``=name;`` で参照する**
(TOPAS には GSAS の「1 相を複数ヒストグラムが共有する」ネイティブ機構が無いため)。
"""

from __future__ import annotations

import pytest

from tsumugin.topas.inp import (
    Param,
    PhaseHistogramTerms,
    TopasDocument,
    TopasHistogram,
    TopasPhase,
    TopasSite,
    render_param,
)

# ---------------- Param のレンダリング (TOPAS の @ / 名前 / ! の意味論) ----------------


def test_fixed_anonymous_param_is_a_bare_number():
    assert render_param(Param(9.18)) == "9.18"


def test_refined_anonymous_param_uses_at_sign():
    assert render_param(Param(9.18, refine=True)) == "@ 9.18"


def test_refined_named_param_is_name_then_value():
    """TOPAS では名前付きパラメータは既定で精密化対象 (`a lpa1 9.18`)。"""
    assert render_param(Param(9.18, refine=True, name="lpa1")) == "lpa1 9.18"


def test_fixed_named_param_is_prefixed_with_bang():
    """`!` 接頭辞が「名前は付けるが精密化しない」を表す (共有参照先の固定値に使う)。"""
    assert render_param(Param(9.18, name="lpa1")) == "!lpa1 9.18"


def test_bounds_are_appended_as_min_max():
    out = render_param(Param(9.18, refine=True, minimum=9.0, maximum=9.3))
    assert out == "@ 9.18 min 9.0 max 9.3"


def test_reference_renders_as_equation():
    """他パラメータの参照は `=name;` (joint の構造共有で使う中核)。"""
    assert render_param(Param.reference("lpa1")) == "=lpa1;"


def test_param_is_frozen():
    with pytest.raises(Exception):
        Param(1.0).value = 2.0  # type: ignore[misc]


# ---------------- 単一ヒストグラムの全体レンダリング ----------------


def _pbso4_phase(**kw) -> TopasPhase:
    return TopasPhase(
        phase_name="PbSO4",
        space_group="P_n_m_a",
        cell={"a": Param(8.482), "b": Param(5.397), "c": Param(6.959)},
        sites=(
            TopasSite("Pb", "Pb+2", Param(0.1879), Param(0.25), Param(0.1667), beq=Param(1.5)),
            TopasSite("S", "S", Param(0.4367), Param(0.75), Param(0.1842), beq=Param(0.7)),
        ),
        **kw,
    )


def _histogram(**kw) -> TopasHistogram:
    return TopasHistogram(
        data_path="pbso4.xye",
        preamble=("CuKa5(0.001)", "LP_Factor(26.37)"),
        background=Param(0.0, refine=True),
        background_coeffs=6,
        **kw,
    )


def test_single_histogram_document_is_a_stable_golden():
    doc = TopasDocument(
        histograms=(_histogram(),),
        phases=(_pbso4_phase(),),
        max_iterations=100,
    )
    assert doc.render() == (
        "' generated by tsumugin (do not edit by hand)\n"
        "r_p 0 r_wp 0 r_exp 0 gof 0\n"
        "r_wp_dash 0 r_exp_dash 0\n"
        "do_errors\n"
        "iters 100\n"
        "\n"
        "xdd \"pbso4.xye\"\n"
        "   CuKa5(0.001)\n"
        "   LP_Factor(26.37)\n"
        "   bkg @ 0.0 0.0 0.0 0.0 0.0 0.0\n"
        "\n"
        "   str\n"
        "      phase_name \"PbSO4\"\n"
        "      space_group P_n_m_a\n"
        "      a 8.482\n"
        "      b 5.397\n"
        "      c 6.959\n"
        "      site Pb x 0.1879 y 0.25 z 0.1667 occ Pb+2 1.0 beq 1.5\n"
        "      site S x 0.4367 y 0.75 z 0.1842 occ S 1.0 beq 0.7\n"
        "      scale 0.0001\n"
        "      MVW(0, 0, mvw_wt_PbSO4 0)\n"
    )


def test_render_is_deterministic():
    """同じ入力からビット同一 (NFR-102)。"""
    a = TopasDocument(histograms=(_histogram(),), phases=(_pbso4_phase(),)).render()
    b = TopasDocument(histograms=(_histogram(),), phases=(_pbso4_phase(),)).render()
    assert a == b


def test_refined_cell_and_sites_carry_the_at_sign():
    phase = _pbso4_phase()
    phase = phase.with_updates(
        cell={k: Param(v.value, refine=True) for k, v in phase.cell.items()}
    )
    text = TopasDocument(histograms=(_histogram(),), phases=(phase,)).render()
    assert "      a @ 8.482\n" in text
    assert "      b @ 5.397\n" in text


def test_two_theta_limits_become_start_x_finish_x():
    hist = _histogram(two_theta_limits=(15.0, 120.0))
    text = TopasDocument(histograms=(hist,), phases=(_pbso4_phase(),)).render()
    assert "   start_X 15.0\n" in text
    assert "   finish_X 120.0\n" in text


def test_excluded_regions_become_exclude_blocks():
    hist = _histogram(excluded_regions=((37.5, 39.0), (44.0, 45.5)))
    text = TopasDocument(histograms=(hist,), phases=(_pbso4_phase(),)).render()
    assert "   exclude 37.5 39.0\n" in text
    assert "   exclude 44.0 45.5\n" in text


def test_neutron_histogram_declares_neutron_data():
    hist = _histogram(is_neutron=True)
    text = TopasDocument(histograms=(hist,), phases=(_pbso4_phase(),)).render()
    assert "   neutron_data\n" in text


def test_tof_histogram_uses_tof_block():
    hist = TopasHistogram(
        data_path="powgen.xye",
        is_neutron=True,
        is_tof=True,
        tof_calibration={"difc": 22580.0, "difa": -1.2, "zero": -4.5},
        background=Param(0.0, refine=True),
        background_coeffs=4,
    )
    text = TopasDocument(histograms=(hist,), phases=(_pbso4_phase(),)).render()
    assert "TOF_XYE(\"powgen.xye\", 0)" in text
    assert "TOF_x_axis_calibration(!difc_h0, 22580.0, !difa_h0, -1.2, !t0_h0, -4.5)" in text
    assert "   neutron_data\n" in text


def test_phase_histogram_terms_render_inside_the_str_block():
    """size/mustrain と scale は**ヒストグラムと相の組**に属する (GSAS の HAP と同じ概念)。"""
    hist = _histogram(
        phase_terms={"PbSO4": PhaseHistogramTerms(
            scale=Param(2e-4, refine=True),
            size_lorentzian=Param(200.0, refine=True),
            strain_lorentzian=Param(0.01, refine=True),
        )}
    )
    text = TopasDocument(histograms=(hist,), phases=(_pbso4_phase(),)).render()
    assert "      scale @ 0.0002\n" in text
    assert "      CS_L(@, 200.0)\n" in text
    assert "      Strain_L(@, 0.01)\n" in text


# ---------------- 結果出力ブロック (決定論的パース対象) ----------------


def test_result_output_block_emits_get_expressions():
    """T0 実測: `Out(Get(r_wp), ...)` が最も決定論的なパース対象。"""
    doc = TopasDocument(
        histograms=(_histogram(),), phases=(_pbso4_phase(),), results_path="results.txt"
    )
    text = doc.render()
    assert '   out "results.txt"\n' in text
    assert '   Out(Get(r_wp), "r_wp\\t%.8f\\n")\n' in text
    assert '   Out(Get(gof), "gof\\t%.8f\\n")\n' in text
    assert '   Out(Get(r_exp), "r_exp\\t%.8f\\n")\n' in text


def test_weight_fraction_is_emitted_per_phase():
    """相分率は MVW の weight を Out で吐く (wt% であって Scale ではない — KMnFe 教訓)。"""
    doc = TopasDocument(
        histograms=(_histogram(),), phases=(_pbso4_phase(),), results_path="results.txt"
    )
    text = doc.render()
    # 値側の書式に改行を入れない — 入れると esd が次行へ落ちる (実測)。1 レコード 1 行。
    assert '      Out(mvw_wt_PbSO4, "wt_frac\\tPbSO4\\t%.8f", "\\t%.8f\\n")\n' in text


# ---------------- joint: 構造の共有 ----------------


def test_joint_hoists_structural_params_into_global_prm():
    """複数ヒストグラムでは構造を `prm` へ持ち上げ、各 xdd の str から `=name;` で参照する。"""
    xray = _histogram()
    neutron = TopasHistogram(
        data_path="pbso4.cwn.xye",
        is_neutron=True,
        preamble=("Lam_neutron(1.909)",),
        background=Param(0.0, refine=True),
        background_coeffs=4,
    )
    phase = _pbso4_phase()
    phase = phase.with_updates(cell={k: Param(v.value, refine=True) for k, v in phase.cell.items()})
    text = TopasDocument(histograms=(xray, neutron), phases=(phase,)).render()

    # グローバル prm に構造パラメータが一度だけ宣言される
    assert "prm PbSO4_a 8.482\n" in text
    assert text.count("prm PbSO4_a ") == 1
    # 各 xdd の str は参照式で書かれる (2 ヒストグラム = 2 回)
    assert text.count("      a =PbSO4_a;\n") == 2
    # 座標も共有される
    assert "prm PbSO4_Pb_x 0.1879\n" in text
    assert text.count("site Pb x =PbSO4_Pb_x;") == 2


def test_joint_keeps_scale_and_background_per_histogram():
    """scale/背景/プロファイルは**共有しない** (ヒストグラム固有)。"""
    xray = _histogram(phase_terms={"PbSO4": PhaseHistogramTerms(scale=Param(1e-4, refine=True))})
    neutron = TopasHistogram(
        data_path="n.xye",
        is_neutron=True,
        background=Param(0.0, refine=True),
        background_coeffs=4,
        phase_terms={"PbSO4": PhaseHistogramTerms(scale=Param(5e-5, refine=True))},
    )
    text = TopasDocument(histograms=(xray, neutron), phases=(_pbso4_phase(),)).render()
    assert "      scale @ 0.0001\n" in text
    assert "      scale @ 5e-05\n" in text
    assert "prm PbSO4_scale" not in text  # scale は持ち上げない


def test_histogram_weight_becomes_weighting_directive():
    hist = _histogram(weight=2.5)
    text = TopasDocument(histograms=(hist,), phases=(_pbso4_phase(),)).render()
    assert "   weighting = 2.5;\n" in text


def test_unit_weight_omits_the_weighting_directive():
    text = TopasDocument(histograms=(_histogram(),), phases=(_pbso4_phase(),)).render()
    assert "weighting" not in text


# ---------------- 制約 (占有率和 = 1 / 等値) ----------------


def test_shared_occupancy_group_uses_one_prm_and_its_complement():
    """混合占有サイトは 1 変数 x と 1-x で表す (GSAS の add_EqnConstr 相当)。"""
    phase = TopasPhase(
        phase_name="garnet",
        space_group="I_a_-3_d",
        cell={"a": Param(12.19, refine=True)},
        sites=(
            TopasSite("Fe1", "Fe+3", Param(0.0), Param(0.0), Param(0.0),
                      occupancy=Param(0.5, refine=True), beq=Param(0.5)),
            TopasSite("Al1", "Al+3", Param(0.0), Param(0.0), Param(0.0),
                      occupancy=Param(0.5), beq=Param(0.5)),
        ),
        occupancy_sum_groups=(("Fe1", "Al1"),),
    )
    text = TopasDocument(histograms=(_histogram(),), phases=(phase,)).render()
    assert "prm garnet_occ_g0 0.5 min 0 max 1\n" in text
    assert "occ Fe+3 =garnet_occ_g0;" in text
    assert "occ Al+3 =1-garnet_occ_g0;" in text


def test_equivalent_beq_group_shares_one_prm():
    phase = TopasPhase(
        phase_name="garnet",
        space_group="I_a_-3_d",
        cell={"a": Param(12.19)},
        sites=(
            TopasSite("Fe1", "Fe+3", Param(0.0), Param(0.0), Param(0.0), beq=Param(0.5)),
            TopasSite("Al1", "Al+3", Param(0.0), Param(0.0), Param(0.0), beq=Param(0.5)),
        ),
        beq_equiv_groups=(("Fe1", "Al1"),),
    )
    text = TopasDocument(histograms=(_histogram(),), phases=(phase,)).render()
    assert "prm garnet_beq_g0 0.5\n" in text
    assert text.count("beq =garnet_beq_g0;") == 2


# ---------------- 安全性 ----------------


def test_data_paths_with_backslashes_are_quoted():
    """Windows パスがそのまま埋まっても INP が壊れないこと。"""
    hist = _histogram()
    hist = hist.with_updates(data_path=r"C:\data\my run\pbso4.xye")
    text = TopasDocument(histograms=(hist,), phases=(_pbso4_phase(),)).render()
    assert 'xdd "C:\\data\\my run\\pbso4.xye"' in text


def test_phase_name_with_spaces_is_quoted():
    phase = _pbso4_phase().with_updates(phase_name="lead sulfate")
    text = TopasDocument(histograms=(_histogram(),), phases=(phase,)).render()
    assert '      phase_name "lead sulfate"\n' in text
