"""Tsumugin — 多仮説・全自動 Rietveld 解析プラットフォーム (PoC / M0 + M1 + M2 + M3 + M4 + M5)."""

from __future__ import annotations

# 各サブパッケージ実体からの re-export (サブパッケージ名のアルファベット昇順で配置)。
# M0/M1/M2/M3/M4 の公開面をトップレベル tsumugin 名前空間へ集約する (別実装でなく is 同一実体 / REQ-404)。
from .absorption import AbsorptionConfig, transmission_factor
from .backends.base import RefinementBackend, RefinementModel, RefinementResult
from .backends.simulated import SimulatedBackend
from .chem import (
    AlkaliMetalInAirRule,
    ChemPlausibility,
    PlausibilityResult,
    SynthesisContext,
    combine_plausibility,
    rank_with_plausibility,
)
from .errors import (
    MCPUnavailableError,
    MEMUnavailableError,
    NestedUnavailableError,
    OEDUnavailableError,
)
from .evidence.ic import AICBackend, BICBackend
from .evidence.ranking import RankedHypothesis, rank
from .export import export_gpx

# 【M4 mcp 遅延 import 契約 (REQ-403)】: create_mcp_server は SDK 非依存で re-export 可能。
# mcp.server は関数内で mcp SDK を遅延 import するため、この re-export はトップレベルで
# mcp SDK を引き込まない (コア import が numpy のみを維持 / TC-408-04)。8 ツールは mcp サブ
# パッケージ側公開のままとし、トップレベル __all__ には AnalysisSession/create_mcp_server のみ載せる。
from .joint import (
    NEUTRON_B_TABLE,
    XRAY_Z_TABLE,
    ContrastConfig,
    HistogramWeighting,
    JointHistogram,
    JointRefinementModel,
    JointRefinementResult,
    JointVerificationResult,
    OccupancyReleaseRecommendation,
    PerHistogramMetrics,
    recommend_occupancy_release,
    refine_joint,
    refine_joint_detailed,
    verify_survivors,
)
from .mcp import AnalysisSession, create_mcp_server
from .model import (
    BeamConfig,
    CellConfig,
    CellLayer,
    ExternalChannel,
    Hypothesis,
    LatticeParams,
    MuCalculator,
    PhaseInstance,
    PhaseLifecycle,
    PhaseRef,
    Project,
    RefinementMetrics,
    TofBankParams,
    XraylibMuCalculator,
)
from .multistart import (
    BasinInfo,
    MultistartConfig,
    MultistartEngine,
    MultistartResult,
    PerturbationSpec,
    cluster_basins,
    generate_starts,
)
from .operando import (
    CELL_PHASE_PRESETS,
    BiologicMprLoader,
    BranchComparison,
    DiscriminationConfig,
    DiscriminationResult,
    EchemData,
    EchemLoader,
    FixedPhaseSpec,
    SegmentationConfig,
    SegmentationResult,
    TransitionPoint,
    branch_differences,
    combined_csv,
    discriminate_interval,
    fixed_free_suffixes,
    read_echem_csv,
    segment_series,
    split_branches,
    transition_point,
)
from .pipeline import AnalysisResult, analyze_single_pattern
from .refinement.staged import RefinementReport, StagedRefinementEngine
from .search import (
    HypothesisTreeSearch,
    Peak,
    PhaseCandidate,
    SearchConfig,
    SearchResult,
    UnmatchedPeakReport,
)
from .selection import (
    Decision,
    FinalSelectionEngine,
    ReviewItem,
    ReviewQueue,
    detect_escalations,
)
from .sequential import (
    ChangepointConfig,
    ChangepointSignal,
    FrameRecord,
    FrameSeries,
    LifecycleConfig,
    LifecycleTracker,
    SequentialConfig,
    SequentialEngine,
    SequentialResult,
    ThermalBaseline,
    Trajectory,
    TransitionEstimate,
    detect_changepoint,
    estimate_transition,
    fit_thermal_baseline,
)
from .store import (
    Ledger,
    PersistentLedger,
    PersistentSnapshotStore,
    SnapshotStore,
    phase_from_dict,
    phase_to_dict,
)

# 【M5 公開面統合 (REQ-404 / TASK-0058)】: nested/mem/oed のコア公開シンボル 40 個を is-同一実体で
# トップレベルへ集約する。実サンプラ (dynesty/ultranest)・実バイナリ (Dysnomia)・pyboed は各境界の
# 関数内/遅延 import に隔離されているため、この re-export はコア import (numpy のみ) を維持する
# (NestedBackend/DysnomiaBackend/acquire を載せても extra を引き込まない, REQ-403)。
from .mem import (
    BondPathDensity,
    DensityCrossSection,
    DysnomiaBackend,
    MEMApplicabilityReport,
    MEMBackend,
    MEMDensityMap,
    MEMInput,
    MEMResult,
    MEMRietveldConfig,
    MEMRietveldResult,
    StructureFactor,
    build_mem_input,
    check_mem_applicability,
    extract_structure_factors,
    run_mem_rietveld,
    run_mem_spot,
)
from .nested import (
    ArbitratedHypothesis,
    ArbitrationConfig,
    ArbitrationResult,
    CalibrationReport,
    CalibrationSample,
    EvidenceProblem,
    LaplaceBackend,
    NestedBackend,
    NestedConfig,
    NestedOutcome,
    PriorSpec,
    ProblemAwareEvidenceBackend,
    ReliabilityBin,
    RestraintSpec,
    arbitrate,
    build_prior_from_restraints,
    calibrate_by_backend,
    expected_calibration_error,
    reliability_diagram,
)
from .oed import (
    OEDProposal,
    acquire,
    propose_measurements,
)

__version__ = "0.1.0"

# アルファベット昇順を維持する (公開面の一貫性。test_m1〜m5_symbols_in_dunder_all_and_sorted が固定)。
# M5 (nested/mem/oed の 40 シンボル + errors.Nested・OEDUnavailableError) 分は非破壊追記。
# 既存 M0/M1/M2/M3/M4 公開面 (111 シンボル) は不変 (REQ-404)。合計 151 シンボル。
__all__ = [
    "AICBackend",
    "AbsorptionConfig",
    "AlkaliMetalInAirRule",
    "AnalysisResult",
    "AnalysisSession",
    "ArbitratedHypothesis",
    "ArbitrationConfig",
    "ArbitrationResult",
    "BICBackend",
    "BasinInfo",
    "BeamConfig",
    "BiologicMprLoader",
    "BondPathDensity",
    "BranchComparison",
    "CELL_PHASE_PRESETS",
    "CalibrationReport",
    "CalibrationSample",
    "CellConfig",
    "CellLayer",
    "ChangepointConfig",
    "ChangepointSignal",
    "ChemPlausibility",
    "ContrastConfig",
    "Decision",
    "DensityCrossSection",
    "DiscriminationConfig",
    "DiscriminationResult",
    "DysnomiaBackend",
    "EchemData",
    "EchemLoader",
    "EvidenceProblem",
    "ExternalChannel",
    "FinalSelectionEngine",
    "FixedPhaseSpec",
    "FrameRecord",
    "FrameSeries",
    "HistogramWeighting",
    "Hypothesis",
    "HypothesisTreeSearch",
    "JointHistogram",
    "JointRefinementModel",
    "JointRefinementResult",
    "JointVerificationResult",
    "LaplaceBackend",
    "LatticeParams",
    "Ledger",
    "LifecycleConfig",
    "LifecycleTracker",
    "MCPUnavailableError",
    "MEMApplicabilityReport",
    "MEMBackend",
    "MEMDensityMap",
    "MEMInput",
    "MEMResult",
    "MEMRietveldConfig",
    "MEMRietveldResult",
    "MEMUnavailableError",
    "MuCalculator",
    "MultistartConfig",
    "MultistartEngine",
    "MultistartResult",
    "NEUTRON_B_TABLE",
    "NestedBackend",
    "NestedConfig",
    "NestedOutcome",
    "NestedUnavailableError",
    "OEDProposal",
    "OEDUnavailableError",
    "OccupancyReleaseRecommendation",
    "Peak",
    "PerHistogramMetrics",
    "PersistentLedger",
    "PersistentSnapshotStore",
    "PerturbationSpec",
    "PhaseCandidate",
    "PhaseInstance",
    "PhaseLifecycle",
    "PhaseRef",
    "PlausibilityResult",
    "PriorSpec",
    "ProblemAwareEvidenceBackend",
    "Project",
    "RankedHypothesis",
    "RefinementBackend",
    "RefinementMetrics",
    "RefinementModel",
    "RefinementReport",
    "RefinementResult",
    "ReliabilityBin",
    "RestraintSpec",
    "ReviewItem",
    "ReviewQueue",
    "SearchConfig",
    "SearchResult",
    "SegmentationConfig",
    "SegmentationResult",
    "SequentialConfig",
    "SequentialEngine",
    "SequentialResult",
    "SimulatedBackend",
    "SnapshotStore",
    "StagedRefinementEngine",
    "StructureFactor",
    "SynthesisContext",
    "ThermalBaseline",
    "TofBankParams",
    "Trajectory",
    "TransitionEstimate",
    "TransitionPoint",
    "UnmatchedPeakReport",
    "XRAY_Z_TABLE",
    "XraylibMuCalculator",
    "acquire",
    "analyze_single_pattern",
    "arbitrate",
    "branch_differences",
    "build_mem_input",
    "build_prior_from_restraints",
    "calibrate_by_backend",
    "check_mem_applicability",
    "cluster_basins",
    "combine_plausibility",
    "combined_csv",
    "create_mcp_server",
    "detect_changepoint",
    "detect_escalations",
    "discriminate_interval",
    "estimate_transition",
    "expected_calibration_error",
    "export_gpx",
    "extract_structure_factors",
    "fit_thermal_baseline",
    "fixed_free_suffixes",
    "generate_starts",
    "phase_from_dict",
    "phase_to_dict",
    "propose_measurements",
    "rank",
    "rank_with_plausibility",
    "read_echem_csv",
    "recommend_occupancy_release",
    "refine_joint",
    "refine_joint_detailed",
    "reliability_diagram",
    "run_mem_rietveld",
    "run_mem_spot",
    "segment_series",
    "split_branches",
    "transition_point",
    "transmission_factor",
    "verify_survivors",
]
